defmodule BashStartpage.Repo.Migrations.AddStartpageResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:startpage_settings, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :offset, :bigint, null: false
      add :timezone, :text
      add :theme, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:sites, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :position, :bigint
      add :tags, {:array, :text}, default: []
      add :shortcuts, {:array, :text}, default: []
      add :url, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:sites)

    drop table(:startpage_settings)
  end
end